import type { Language } from './LanguageContext'

type L = Exclude<Language, 'en'>
type T = [string, string, string]
const p: Record<string, T> = {
  'Travel': ['Reisen','Voyages','Podróże'],
  'Visited 52 countries & territories': ['52 Länder und Gebiete besucht','52 pays et territoires visités','Odwiedzone 52 kraje i terytoria'],
  'Favorite books': ['Lieblingsbücher','Livres préférés','Ulubione książki'],
  'Favorite television': ['Lieblingsserien','Séries préférées','Ulubione seriale'],
  'Web Development': ['Webentwicklung','Développement web','Tworzenie stron internetowych'],
  'Building full-stack experiences with HTML, CSS, JavaScript, React, APIs, and modern web tooling.': ['Full-Stack-Anwendungen mit HTML, CSS, JavaScript, React, APIs und modernen Webwerkzeugen.','Création d’expériences full-stack avec HTML, CSS, JavaScript, React, des API et des outils web modernes.','Tworzenie aplikacji full-stack z HTML, CSS, JavaScript, React, API i nowoczesnymi narzędziami webowymi.'],
  'My primary languages for performant algorithms, systems software, simulations, and large-scale data structures.': ['Meine wichtigsten Sprachen für leistungsfähige Algorithmen, Systemsoftware, Simulationen und große Datenstrukturen.','Mes langages principaux pour les algorithmes performants, les logiciels système, les simulations et les grandes structures de données.','Moje główne języki do wydajnych algorytmów, oprogramowania systemowego, symulacji i dużych struktur danych.'],
  'A preferred language for machine learning, graph problems, APIs, data workflows, and algorithm practice.': ['Meine bevorzugte Sprache für maschinelles Lernen, Graphenprobleme, APIs, Datenabläufe und Algorithmen.','Mon langage privilégié pour l’apprentissage automatique, les graphes, les API, les flux de données et les algorithmes.','Preferowany język do uczenia maszynowego, grafów, API, przetwarzania danych i algorytmów.'],
  'Designing reliable database operations and efficient back-end data flows for full-stack applications.': ['Zuverlässige Datenbankoperationen und effiziente Backend-Datenflüsse für Full-Stack-Anwendungen.','Conception d’opérations de base de données fiables et de flux backend efficaces pour les applications full-stack.','Projektowanie niezawodnych operacji bazodanowych i wydajnych przepływów backendowych.'],
  'Developing models with Python, Keras, TensorFlow, C++, computer vision architectures, and custom optimization methods.': ['Modellentwicklung mit Python, Keras, TensorFlow, C++, Computer-Vision-Architekturen und eigenen Optimierungsmethoden.','Développement de modèles avec Python, Keras, TensorFlow, C++, des architectures de vision et des méthodes d’optimisation personnalisées.','Tworzenie modeli w Pythonie, Keras, TensorFlow i C++ z architekturami wizji komputerowej i własną optymalizacją.'],
  'Geography': ['Geografie','Géographie','Geografia'],
  'A lifelong interest in countries, capitals, flags, mapping, navigation, and the technology behind digital maps.': ['Ein lebenslanges Interesse an Ländern, Hauptstädten, Flaggen, Kartografie, Navigation und digitaler Kartentechnik.','Un intérêt de toujours pour les pays, capitales, drapeaux, cartes, la navigation et les technologies cartographiques.','Wieloletnie zainteresowanie krajami, stolicami, flagami, kartografią, nawigacją i technologią map cyfrowych.'],
  'Experience': ['Berufserfahrung','Expérience','Doświadczenie'],
  'Building for real-world scale.': ['Entwicklung für reale Größenordnungen.','Concevoir à l’échelle du monde réel.','Tworzenie na skalę rzeczywistego świata.'],
  'Software Development Engineer': ['Softwareentwicklungsingenieur','Ingénieur en développement logiciel','Inżynier oprogramowania'],
  'Full-time': ['Vollzeit','Temps plein','Pełny etat'],
  'Engineering reliable software for high-throughput environments, with a focus on scalable architecture, operational excellence, and thoughtful execution.': ['Entwicklung zuverlässiger Software für Umgebungen mit hohem Durchsatz, mit Fokus auf skalierbare Architektur, Betriebsqualität und sorgfältige Umsetzung.','Conception de logiciels fiables pour des environnements à haut débit, axée sur une architecture évolutive, l’excellence opérationnelle et une exécution réfléchie.','Tworzenie niezawodnego oprogramowania dla środowisk o dużej przepustowości, ze skalowalną architekturą i wysoką jakością operacyjną.'],
  'Large-scale systems': ['Großskalige Systeme','Systèmes à grande échelle','Systemy wielkoskalowe'], 'Cloud infrastructure': ['Cloud-Infrastruktur','Infrastructure cloud','Infrastruktura chmurowa'], 'Software design': ['Softwaredesign','Conception logicielle','Projektowanie oprogramowania'],
  '2024 — Present': ['2024 — heute','2024 — aujourd’hui','2024 — obecnie'],
  'Education': ['Ausbildung','Formation','Wykształcenie'], 'A fast, focused foundation.': ['Ein schneller, fokussierter Grundstein.','Des bases rapides et ciblées.','Szybkie i ukierunkowane fundamenty.'],
  'M.S. Computer Engineering': ['M.S. Computer Engineering','Master en génie informatique','Magister inżynierii komputerowej'], 'B.S. Computer Engineering': ['B.S. Computer Engineering','Licence en génie informatique','Inżynieria komputerowa — licencjat'], 'Associate Degree': ['Associate Degree','Diplôme universitaire associé','Stopień Associate'],
  'Completed while working full-time.': ['Parallel zu einer Vollzeitstelle abgeschlossen.','Obtenu tout en travaillant à temps plein.','Ukończone podczas pracy na pełny etat.'], 'Completed at age 21.': ['Mit 21 Jahren abgeschlossen.','Obtenu à 21 ans.','Ukończone w wieku 21 lat.'], 'Early college program': ['Frühes College-Programm','Programme universitaire anticipé','Program wczesnych studiów'], 'Completed at age 18.': ['Mit 18 Jahren abgeschlossen.','Obtenu à 18 ans.','Ukończone w wieku 18 lat.'],
  '26 projects across systems, machine learning, algorithms, web development, optimization, and quantum computing.': ['26 Projekte aus Systemtechnik, maschinellem Lernen, Algorithmen, Webentwicklung, Optimierung und Quanteninformatik.','26 projets couvrant les systèmes, l’apprentissage automatique, les algorithmes, le web, l’optimisation et l’informatique quantique.','26 projektów z systemów, uczenia maszynowego, algorytmów, aplikacji webowych, optymalizacji i informatyki kwantowej.'],
  'GitHub archive': ['GitHub-Archiv','Archives GitHub','Archiwum GitHub'], 'Search projects': ['Projekte durchsuchen','Rechercher des projets','Szukaj projektów'], 'Search projects or technologies': ['Projekte oder Technologien suchen','Rechercher des projets ou technologies','Szukaj projektów lub technologii'], 'Filter projects by category': ['Projekte nach Kategorie filtern','Filtrer les projets par catégorie','Filtruj projekty według kategorii'], 'No projects match that filter.': ['Keine Projekte entsprechen diesem Filter.','Aucun projet ne correspond à ce filtre.','Żaden projekt nie pasuje do tego filtra.'],
  'Efficient learning systems and practical model intelligence.': ['Effiziente Lernsysteme und praktisch nutzbare Modellintelligenz.','Systèmes d’apprentissage efficaces et intelligence pratique des modèles.','Wydajne systemy uczące i praktyczna inteligencja modeli.'], 'Visual understanding, representation, and perception.': ['Visuelles Verstehen, Repräsentation und Wahrnehmung.','Compréhension visuelle, représentation et perception.','Rozumienie obrazu, reprezentacja i percepcja.'], 'Distributed Systems': ['Verteilte Systeme','Systèmes distribués','Systemy rozproszone'], 'Reliable infrastructure for computation at scale.': ['Zuverlässige Infrastruktur für Berechnungen im großen Maßstab.','Infrastructure fiable pour le calcul à grande échelle.','Niezawodna infrastruktura obliczeniowa na dużą skalę.'], 'Methods that make complex systems faster and better.': ['Methoden, die komplexe Systeme schneller und besser machen.','Méthodes rendant les systèmes complexes plus rapides et performants.','Metody przyspieszające i ulepszające złożone systemy.'], 'Robotics': ['Robotik','Robotique','Robotyka'], 'Intelligence grounded in physical environments.': ['Intelligenz in physischen Umgebungen.','Une intelligence ancrée dans les environnements physiques.','Inteligencja osadzona w środowisku fizycznym.'], 'Algorithms': ['Algorithmen','Algorithmes','Algorytmy'], 'Elegant structures for hard computational problems.': ['Elegante Strukturen für schwierige Rechenprobleme.','Des structures élégantes pour des problèmes informatiques difficiles.','Eleganckie struktury dla trudnych problemów obliczeniowych.'],
  'Machine Learning': ['Maschinelles Lernen','Apprentissage automatique','Uczenie maszynowe'], 'Computer Vision': ['Computer Vision','Vision par ordinateur','Wizja komputerowa'], 'Optimization': ['Optimierung','Optimisation','Optymalizacja'],
  'Timeline': ['Zeitleiste','Parcours','Oś czasu'], 'Momentum, over milestones.': ['Fortschritt über Meilensteine hinweg.','L’élan au fil des étapes.','Rozwój poprzez kolejne etapy.'], 'Associate degree': ['Associate Degree','Diplôme associé','Stopień Associate'], 'Completed an accelerated early-college path at 18.': ['Mit 18 einen beschleunigten College-Weg abgeschlossen.','Parcours universitaire accéléré terminé à 18 ans.','Przyspieszony program studiów ukończony w wieku 18 lat.'], 'Bachelor’s + Amazon': ['Bachelor + Amazon','Licence + Amazon','Licencjat + Amazon'], 'Earned a B.S. in Computer Engineering and began building at Amazon.': ['B.S. in Computer Engineering abgeschlossen und bei Amazon begonnen.','Licence en génie informatique obtenue et début chez Amazon.','Ukończenie inżynierii komputerowej i rozpoczęcie pracy w Amazon.'], 'Master’s degree': ['Masterabschluss','Master','Magister'], 'Completed an M.S. in Computer Engineering at Michigan while working full-time.': ['M.S. in Computer Engineering in Michigan parallel zur Vollzeitstelle abgeschlossen.','Master en génie informatique au Michigan obtenu tout en travaillant à temps plein.','Magister inżynierii komputerowej w Michigan ukończony podczas pracy na pełny etat.'], 'Next': ['Als Nächstes','Ensuite','Dalej'], 'The open frontier': ['Offene Horizonte','Un horizon ouvert','Otwarty horyzont'], 'Deeper research, harder systems problems, and work with meaningful reach.': ['Tiefere Forschung, schwierigere Systemprobleme und Arbeit mit bedeutender Wirkung.','Des recherches plus poussées, des systèmes plus difficiles et un travail à portée réelle.','Głębsze badania, trudniejsze problemy systemowe i praca o znaczącym wpływie.'],
  'Travel atlas': ['Reiseatlas','Atlas de voyage','Atlas podróży'], 'The world, explored.': ['Die Welt, erkundet.','Le monde, exploré.','Świat odkryty.'], 'A living map of the cities, landmarks, countries, and territories that have shaped my view of the world.': ['Eine lebendige Karte der Städte, Orte, Länder und Gebiete, die meinen Blick auf die Welt geprägt haben.','Une carte vivante des villes, lieux, pays et territoires qui ont façonné ma vision du monde.','Żywa mapa miast, miejsc, krajów i terytoriów, które ukształtowały moje spojrzenie na świat.'],
  'Cities lived in': ['Wohnorte','Villes habitées','Miasta zamieszkania'], 'Places called home': ['Orte, die Heimat waren','Lieux appelés chez moi','Miejsca nazywane domem'], 'Places visited': ['Besuchte Orte','Lieux visités','Odwiedzone miejsca'], 'Cities and landmarks': ['Städte und Sehenswürdigkeiten','Villes et monuments','Miasta i zabytki'], 'Countries & territories': ['Länder und Gebiete','Pays et territoires','Kraje i terytoria'], 'National overview': ['Länderübersicht','Vue nationale','Przegląd krajów'],
  'lived in': ['gelebt','habitées','zamieszkałe'], 'visited': ['besucht','visités','odwiedzone'], 'countries': ['Länder','pays','kraje'], 'country': ['Land','pays','kraj'], 'Search travel locations': ['Reiseorte durchsuchen','Rechercher des lieux','Szukaj miejsc podróży'], 'Clear search': ['Suche löschen','Effacer la recherche','Wyczyść wyszukiwanie'], 'Interactive map of places Ashton has visited': ['Interaktive Karte der von Ashton besuchten Orte','Carte interactive des lieux visités par Ashton','Interaktywna mapa miejsc odwiedzonych przez Ashtona'], 'World view': ['Weltansicht','Vue mondiale','Widok świata'], 'Close location details': ['Ortsdetails schließen','Fermer les détails du lieu','Zamknij szczegóły miejsca'],
  'Map data migrated from the original travel atlas. Tiles by OpenStreetMap and CARTO; boundaries by Natural Earth and geoBoundaries.': ['Kartendaten aus dem ursprünglichen Reiseatlas. Karten von OpenStreetMap und CARTO; Grenzen von Natural Earth und geoBoundaries.','Données issues de l’atlas original. Tuiles par OpenStreetMap et CARTO ; frontières par Natural Earth et geoBoundaries.','Dane przeniesione z pierwotnego atlasu. Kafelki OpenStreetMap i CARTO; granice Natural Earth i geoBoundaries.'],
}

const languages: L[] = ['de', 'fr', 'pl']
export const sectionPhrases = Object.fromEntries(languages.map((language, index) => [language, Object.fromEntries(Object.entries(p).map(([source, values]) => [source, values[index]]))])) as Record<L, Record<string, string>>
