const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const imageRoot = path.join(root, 'public', 'images')
const outputPath = path.join(root, 'src', 'data', 'heroImages.generated.ts')
const supportedExtensions = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif'])

const formatLabel = (fileName) => fileName
  .replace(/\.[^.]+$/, '')
  .replace(/[-_]+/g, ' ')
  .trim()
  .toUpperCase()

const readHeroFolder = (folder, position) => {
  const fullPath = path.join(imageRoot, folder)
  if (!fs.existsSync(fullPath)) return []

  return fs.readdirSync(fullPath, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .filter((entry) => supportedExtensions.has(path.extname(entry.name).toLowerCase()))
    .map((entry) => ({
      src: `/images/${folder}/${entry.name}`,
      label: formatLabel(entry.name),
      position,
    }))
    .sort((a, b) => a.label.localeCompare(b.label))
}

const landscapeHeroImages = readHeroFolder('hero-landscape', 'center 48%')
const portraitHeroImages = readHeroFolder('hero-portrait', 'center 42%')

const contents = `// This file is auto-generated by scripts/generateHeroImages.cjs.
// Do not edit by hand. Add/remove files in public/images/hero-landscape or public/images/hero-portrait instead.

export type HeroImage = { src: string, label: string, position: string }

export const landscapeHeroImages: HeroImage[] = ${JSON.stringify(landscapeHeroImages, null, 2)}

export const portraitHeroImages: HeroImage[] = ${JSON.stringify(portraitHeroImages, null, 2)}
`

fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, contents)
console.log(`Generated ${path.relative(root, outputPath)} with ${landscapeHeroImages.length} landscape and ${portraitHeroImages.length} portrait hero images.`)
