// This file is auto-generated by scripts/generateHeroImages.cjs.
// Do not edit by hand. Add/remove files in public/images/hero-landscape or public/images/hero-portrait instead.

export type HeroImage = { src: string, label: string, position: string }

export const landscapeHeroImages: HeroImage[] = [
  {
    "src": "/images/hero-landscape/Downtown_Matsuyama.jpg",
    "label": "DOWNTOWN MATSUYAMA",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Fuji.jpeg",
    "label": "FUJI",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Gibraltar.JPG",
    "label": "GIBRALTAR",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Gros_Piton.jpeg",
    "label": "GROS PITON",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Honolulu.jpg",
    "label": "HONOLULU",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Kyoto.jpeg",
    "label": "KYOTO",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Malbun.JPG",
    "label": "MALBUN",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Marigot.jpeg",
    "label": "MARIGOT",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Matsuyama.jpeg",
    "label": "MATSUYAMA",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Osaka.jpeg",
    "label": "OSAKA",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Sapporo.jpeg",
    "label": "SAPPORO",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Singapore.jpeg",
    "label": "SINGAPORE",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Sydney.jpeg",
    "label": "SYDNEY",
    "position": "center 48%"
  },
  {
    "src": "/images/hero-landscape/Vatican.jpeg",
    "label": "VATICAN",
    "position": "center 48%"
  }
]

export const portraitHeroImages: HeroImage[] = [
  {
    "src": "/images/hero-portrait/Hanoi.png",
    "label": "HANOI",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Hill_of_the_Buddha.jpeg",
    "label": "HILL OF THE BUDDHA",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Kyoto.jpeg",
    "label": "KYOTO",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/San Marino.jpeg",
    "label": "SAN MARINO",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Sapporo.jpeg",
    "label": "SAPPORO",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Singapore.jpeg",
    "label": "SINGAPORE",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Sydney.jpeg",
    "label": "SYDNEY",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Sydney_Zoo.jpeg",
    "label": "SYDNEY ZOO",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Tokyo.jpeg",
    "label": "TOKYO",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Victoria.jpeg",
    "label": "VICTORIA",
    "position": "center 42%"
  },
  {
    "src": "/images/hero-portrait/Vienna.jpeg",
    "label": "VIENNA",
    "position": "center 42%"
  }
]
